#-------------------------------
# General Site Settings

title: Blog
description: The ramblings of a Cloud Solution Architect with a love for fast .NET code and getting it out to the consumers quickly with good DevOps practices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Ove Bastiansen
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook: # Add your Facebook handle
twitter:   https://twitter.com/ovebastiansen # Add your Facebook handle
linkedin: https://www.linkedin.com/in/ovebastiansen/
github: https://github.com/ovebastiansen
instagram: # Add your Facebook handle
pinterest: # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-173123904-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
#permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

# include:
#   - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
